#!/bin/bash
# Git pre-commit hook to automatically sync package-lock.json
# Install: ln -sf ../../.githooks/pre-commit .git/hooks/pre-commit

export GIT_HOOK="pre-commit"

# Run the sync script
./scripts/sync-lockfile.sh

exit $?
